FROM python:3.12-slim
ENV APP_HOME=/app
WORKDIR $APP_HOME
COPY ./requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY ./backend/ ./
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "2", "app:app"]
