apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: frontend-hpa
  namespace: trip-planner
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: frontend-d

  minReplicas: 1
  maxReplicas: 3

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40 
