apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-pvc
  namespace: trip-planner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: dummyfrontend 
  resources:
    requests:
      storage: 1Gi
      

