apiVersion: v1
kind: PersistentVolume
metadata:
  name: frontend-pv
spec:
  capacity:
    storage: 1.5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: dummyfrontend
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/nodevol-frontend 
