apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs
  namespace: nfs-nfs
spec:
  accessModes: 
  - ReadWriteMany
  storageClassName: nfs-sc
  resources:
    requests:
      storage: 800Mi

